/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PartnerWithUsRouteImport } from './routes/partner-with-us'
import { Route as NewsRouteImport } from './routes/news'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClinicalEvidenceRouteImport } from './routes/clinical-evidence'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsSleepMedicineRouteImport } from './routes/solutions.sleep-medicine'
import { Route as SolutionsOperatingRoomRouteImport } from './routes/solutions.operating-room'
import { Route as SolutionsHomeMonitoringRouteImport } from './routes/solutions.home-monitoring'
import { Route as SolutionsCriticalCareRouteImport } from './routes/solutions.critical-care'
import { Route as SolutionsAnesthesiologyRouteImport } from './routes/solutions.anesthesiology'

const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithUsRoute = PartnerWithUsRouteImport.update({
  id: '/partner-with-us',
  path: '/partner-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalEvidenceRoute = ClinicalEvidenceRouteImport.update({
  id: '/clinical-evidence',
  path: '/clinical-evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSleepMedicineRoute = SolutionsSleepMedicineRouteImport.update({
  id: '/sleep-medicine',
  path: '/sleep-medicine',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsOperatingRoomRoute = SolutionsOperatingRoomRouteImport.update({
  id: '/operating-room',
  path: '/operating-room',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsHomeMonitoringRoute = SolutionsHomeMonitoringRouteImport.update({
  id: '/home-monitoring',
  path: '/home-monitoring',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsCriticalCareRoute = SolutionsCriticalCareRouteImport.update({
  id: '/critical-care',
  path: '/critical-care',
  getParentRoute: () => SolutionsRoute,
} as any)
const SolutionsAnesthesiologyRoute = SolutionsAnesthesiologyRouteImport.update({
  id: '/anesthesiology',
  path: '/anesthesiology',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clinical-evidence': typeof ClinicalEvidenceRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/news': typeof NewsRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/product': typeof ProductRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/solutions/anesthesiology': typeof SolutionsAnesthesiologyRoute
  '/solutions/critical-care': typeof SolutionsCriticalCareRoute
  '/solutions/home-monitoring': typeof SolutionsHomeMonitoringRoute
  '/solutions/operating-room': typeof SolutionsOperatingRoomRoute
  '/solutions/sleep-medicine': typeof SolutionsSleepMedicineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clinical-evidence': typeof ClinicalEvidenceRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/news': typeof NewsRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/product': typeof ProductRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/solutions/anesthesiology': typeof SolutionsAnesthesiologyRoute
  '/solutions/critical-care': typeof SolutionsCriticalCareRoute
  '/solutions/home-monitoring': typeof SolutionsHomeMonitoringRoute
  '/solutions/operating-room': typeof SolutionsOperatingRoomRoute
  '/solutions/sleep-medicine': typeof SolutionsSleepMedicineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clinical-evidence': typeof ClinicalEvidenceRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/news': typeof NewsRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/product': typeof ProductRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/technology': typeof TechnologyRoute
  '/solutions/anesthesiology': typeof SolutionsAnesthesiologyRoute
  '/solutions/critical-care': typeof SolutionsCriticalCareRoute
  '/solutions/home-monitoring': typeof SolutionsHomeMonitoringRoute
  '/solutions/operating-room': typeof SolutionsOperatingRoomRoute
  '/solutions/sleep-medicine': typeof SolutionsSleepMedicineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clinical-evidence'
    | '/contact'
    | '/faq'
    | '/news'
    | '/partner-with-us'
    | '/product'
    | '/solutions'
    | '/technology'
    | '/solutions/anesthesiology'
    | '/solutions/critical-care'
    | '/solutions/home-monitoring'
    | '/solutions/operating-room'
    | '/solutions/sleep-medicine'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clinical-evidence'
    | '/contact'
    | '/faq'
    | '/news'
    | '/partner-with-us'
    | '/product'
    | '/solutions'
    | '/technology'
    | '/solutions/anesthesiology'
    | '/solutions/critical-care'
    | '/solutions/home-monitoring'
    | '/solutions/operating-room'
    | '/solutions/sleep-medicine'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clinical-evidence'
    | '/contact'
    | '/faq'
    | '/news'
    | '/partner-with-us'
    | '/product'
    | '/solutions'
    | '/technology'
    | '/solutions/anesthesiology'
    | '/solutions/critical-care'
    | '/solutions/home-monitoring'
    | '/solutions/operating-room'
    | '/solutions/sleep-medicine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClinicalEvidenceRoute: typeof ClinicalEvidenceRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  NewsRoute: typeof NewsRoute
  PartnerWithUsRoute: typeof PartnerWithUsRoute
  ProductRoute: typeof ProductRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TechnologyRoute: typeof TechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-us': {
      id: '/partner-with-us'
      path: '/partner-with-us'
      fullPath: '/partner-with-us'
      preLoaderRoute: typeof PartnerWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical-evidence': {
      id: '/clinical-evidence'
      path: '/clinical-evidence'
      fullPath: '/clinical-evidence'
      preLoaderRoute: typeof ClinicalEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/sleep-medicine': {
      id: '/solutions/sleep-medicine'
      path: '/sleep-medicine'
      fullPath: '/solutions/sleep-medicine'
      preLoaderRoute: typeof SolutionsSleepMedicineRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/operating-room': {
      id: '/solutions/operating-room'
      path: '/operating-room'
      fullPath: '/solutions/operating-room'
      preLoaderRoute: typeof SolutionsOperatingRoomRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/home-monitoring': {
      id: '/solutions/home-monitoring'
      path: '/home-monitoring'
      fullPath: '/solutions/home-monitoring'
      preLoaderRoute: typeof SolutionsHomeMonitoringRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/critical-care': {
      id: '/solutions/critical-care'
      path: '/critical-care'
      fullPath: '/solutions/critical-care'
      preLoaderRoute: typeof SolutionsCriticalCareRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/anesthesiology': {
      id: '/solutions/anesthesiology'
      path: '/anesthesiology'
      fullPath: '/solutions/anesthesiology'
      preLoaderRoute: typeof SolutionsAnesthesiologyRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsAnesthesiologyRoute: typeof SolutionsAnesthesiologyRoute
  SolutionsCriticalCareRoute: typeof SolutionsCriticalCareRoute
  SolutionsHomeMonitoringRoute: typeof SolutionsHomeMonitoringRoute
  SolutionsOperatingRoomRoute: typeof SolutionsOperatingRoomRoute
  SolutionsSleepMedicineRoute: typeof SolutionsSleepMedicineRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsAnesthesiologyRoute: SolutionsAnesthesiologyRoute,
  SolutionsCriticalCareRoute: SolutionsCriticalCareRoute,
  SolutionsHomeMonitoringRoute: SolutionsHomeMonitoringRoute,
  SolutionsOperatingRoomRoute: SolutionsOperatingRoomRoute,
  SolutionsSleepMedicineRoute: SolutionsSleepMedicineRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClinicalEvidenceRoute: ClinicalEvidenceRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  NewsRoute: NewsRoute,
  PartnerWithUsRoute: PartnerWithUsRoute,
  ProductRoute: ProductRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  TechnologyRoute: TechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
